yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Группа',
                             max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField('Группа')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации',
                                    auto_now_add=True,
                                    help_text='Дата публикации')

    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        help_text='Автор поста',
        on_delete=models.CASCADE,
        related_name='posts'
    )

    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date', )

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(
        'Текст комментария',
        help_text='Напишите комментарий'
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='follower', verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='following', verbose_name='На кого подписываемся'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Текст поста', 'group': 'Группа', }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Пост будет относиться к этой группе',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', ]

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.core.paginator import Paginator

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import split_pages


@cache_page(20, key_prefix='index_page')
def index(request):
    posts = Post.objects.select_related('group', 'author').all()
    context = {
        'page_obj': split_pages(posts, request),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related("author", "group")
    context = {
        'group': group,
        'page_obj': split_pages(posts, request),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    user = request.user
    following = (request.user.is_authenticated
                 and author.following.filter(user=user).exists())

    context = {
        'page_obj': split_pages(posts, request),
        'author': author,
        "following": following
    }
    template = 'posts/profile.html'
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('group', 'author'), pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(
            user=request.user, author=post.author
        ).exists()
    )
    context = {'post': post,
               'form': form,
               'comments': comments,
               "following": following}
    return render(request, 'posts/post_detail.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_create(request):
    template = "posts/create_post.html"
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if not form.is_valid():
        context = {"form": form}
        return render(request, template, context)
    new_post = form.save(commit=False)
    new_post.author = request.user
    new_post.save()
    return redirect("posts:profile", username=request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if not form.is_valid():
        is_edit = True
        context = {
            'form': form,
            'is_edit': is_edit
        }
        return render(request, 'posts/create_post.html', context)
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, settings.NUM_POSTS)
    page_obj = split_pages(post_list, request)
    context = {'page_obj': page_obj,
               'paginator': paginator}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(user=user, author=author).exists():
        Follow.objects.filter(user=user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}Новый пост{% endblock %}
{% block content %}
  {% load user_filters %}  
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          Новый пост             
        </div>
        <div class="card-body"> 
          {% include 'includes/forms_error.html' %}  
          <form method="post"
            enctype="multipart/form-data"           
            {% if action_url %} 
             action = "{% url 'action_url' %}"
            {% endif %} 
          >               
          {% csrf_token %}
          {% include 'includes/form_field.html' %}
            <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
        </div>   
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Подписки{% endblock %}
{% block header %}Посты авторов, на которых вы подписаны{% endblock %}
{% block content %}
  {% include "posts/includes/switcher.html" with follow=True %}
    {% for post in page %}
      {% include 'posts/includes/text_post.html' with show_group_link=True show_posts_author=True%}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} {{ group.title }} {% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>
    {{ group.description|linebreaksbr }}
  </p>
  {% for post in page_obj %}
    {% include 'posts/includes/text_post.html'%}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{ 'Последние обновления на сайте' }}{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with index=True%}
    {% for post in page_obj %}
      {% include 'posts/includes/text_post.html' with show_group_link=True show_posts_author=True%}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post|truncatechars:30 }}{% endblock %}
    {% block content %}
          <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y"}}
                  </li>
                  {% if post.groups %}   
                    <li class="list-group-item">
                      Группа:
                      <a href=<a href="{% url 'posts:group' post.group.slug %}">
                        все записи группы
                      </a>
                    </li>
                  {% endif %}
                  {% if not forloop.last %}<hr>{% endif %}
                
                <li class="list-group-item">
                  Автор: {{ post.author.get_full_name }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  Всего постов автора:  <span >{{ post.author.posts.count }}</span>
                </li>
                <li class="list-group-item">
                  <a href="{% url 'posts:profile' post.author.get_username %}"> 
                    все посты пользователя
                  </a>
                </li>
                </ul>
            </aside>
            {% load thumbnail %}
            <article class="col-12 col-md-9">
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
              <p>
                {{ post.text|linebreaksbr }}
                {% include 'posts/includes/comment.html' %}
              </p>
            </article>
          </div>      
    {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
<div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3> 
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
        {% for post in page_obj %}      
            {% include 'posts/includes/text_post.html' with show_group_link=True show_posts_author=True%}
        {% endfor %} 
        {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}